routes.py
from ast import main
import os
from flask import Blueprint, abort, current_app, flash, redirect, render_template, url_for, request
from flask_login import current_user, login_required
from sqlalchemy import func
# from investment_analyses import oer_analysis
from models import MaintainanceReport, Property, Listing, RentalAgreement, Transaction, User, db, Message, Owner, BankingDetails
from datetime import datetime, timedelta, date
from sqlalchemy.orm import joinedload

main = Blueprint('main', __name__)

@main.route('/')
@login_required
def index():
    current_app.logger.info("Index route accessed")
    # Get the filter type from the query parameters, default to 'past_year'
    filter_type = request.args.get('filter', 'past_year')
    # Logic to calculate date ranges based on the filter type
    if filter_type == 'today':
        start_date = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
        end_date = datetime.now().replace(hour=23, minute=59, second=59, microsecond=999999)
    elif filter_type == 'this_month':
        start_date = datetime.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        end_date = datetime.now().replace(day=1, month=datetime.now().month + 1, hour=0, minute=0, second=0, microsecond=0) if datetime.now().month < 12 else datetime.now().replace(year=datetime.now().year + 1, month=1, day=1)
    elif filter_type == 'last_month':
        start_date = (datetime.now().replace(day=1) - timedelta(days=1)).replace(day=1)
        end_date = datetime.now().replace(day=1)
    elif filter_type == 'this_year':
        start_date = datetime.now().replace(month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
        end_date = datetime.now().replace(month=1, day=1, year=datetime.now().year + 1)
    elif filter_type == 'past_year':
        end_date = datetime.now()
        start_date = end_date - timedelta(days=365)
    else:
        # Default to past year if filter type is not recognized
        end_date = datetime.now()
        start_date = end_date - timedelta(days=365)

    active_maintainance = MaintainanceReport.query.filter(
        MaintainanceReport.reported_date >= start_date,
        MaintainanceReport.reported_date <= end_date,
        MaintainanceReport.status == 0,
        MaintainanceReport.property_id.in_(
            db.session.query(Property.id).filter(Property.owner.has(user_id=current_user.id))
        )  # Limit to current user's properties
    ).count()

    total_income = db.session.query(db.func.sum(Transaction.amount)).filter(
        Transaction.main_category == 'Revenue',
        Transaction.transaction_date >= start_date,
        Transaction.transaction_date < end_date,
        Transaction.is_reconciled == True,
        Transaction.owner.has(user_id=current_user.id)  
    ).scalar() or 0  

    total_operating_expenses = db.session.query(db.func.sum(Transaction.amount)).filter(
        Transaction.sub_category == 'Cost of Sales',
        Transaction.transaction_date >= start_date,
        Transaction.transaction_date < end_date,
        Transaction.is_reconciled == True,
        Transaction.owner.has(user_id=current_user.id) 
    ).scalar() or 0

    terminated_rental_agreements = db.session.query(RentalAgreement).filter(
        RentalAgreement.status == 'no_renewal',
        RentalAgreement.date_end >= start_date,
        RentalAgreement.date_end < end_date,
        RentalAgreement.owner.has(user_id=current_user.id)
    ).count() or 0

    tenant_count = active_rental_agreements()
    formatted_income = '{:,.2f}'.format(total_income)
    formatted_operating_expenses = '{:,.2f}'.format(total_operating_expenses)
    user = User.query.options(joinedload(User.currency)).filter_by(id=current_user.id).first()
    
    # Fetch the latest rental agreement for the current user
    agreement = RentalAgreement.query.join(Owner).filter(Owner.user_id == current_user.id).order_by(RentalAgreement.date_created.desc()).first()

    # Fetch the unread messages count
    unread_messages_count = Message.query.filter_by(recipient_id=current_user.id, is_read=False).count()

    # Query to get pending agreements for the current user's owner
    pending_agreements = RentalAgreement.query.filter_by(status='active', owner_id=current_user.id).all()
    progress_data = []

    for agreement in pending_agreements:
        if agreement.date_start and agreement.date_end:
            # Ensure both dates are datetime objects
            date_start = datetime.combine(agreement.date_start, datetime.min.time()) if isinstance(agreement.date_start, date) else agreement.date_start
            date_end = datetime.combine(agreement.date_end, datetime.min.time()) if isinstance(agreement.date_end, date) else agreement.date_end
            
            total_duration = (date_end - date_start).days
            elapsed_time = (datetime.now() - date_start).days
            progress_percentage = 100 - (elapsed_time / total_duration) * 100 if total_duration > 0 else 0
            progress_data.append({
                'property_title': agreement.property.title,
                'progress_percentage': min(max(progress_percentage, 0), 100)  # Clamp between 0 and 100
            })

    # Call the OER analysis function to get the category
    oer_category = oer_analysis()  # Ensure this function returns the category

    # current_app.logger.info(f"Total Operating Expenses: {total_operating_expenses}, Total Income: {total_income}, Operating Expenses Ratio: {operating_expenses_ratio}")

    banking_details_count = BankingDetails.query.filter_by(user_id=current_user.id).count()

    return render_template('dashboard/index.html', user=user, total_income=formatted_income, total_operating_expenses=formatted_operating_expenses, filter=filter_type, terminated_rental_agreements=terminated_rental_agreements, tenant_count=tenant_count, active_maintainance=active_maintainance, agreement=agreement, offer_validity=agreement.offer_validity if agreement else None, unread_messages_count=unread_messages_count, progress_data=progress_data, oer_category=oer_category, banking_details_count=banking_details_count, current_user=current_user)

@main.route('/maintenance')
def maintenance():
    # Fetch all maintenance reports
    reports = MaintainanceReport.query.all()
    
    # Fetch the unread messages count
    unread_messages_count = Message.query.filter_by(recipient_id=current_user.id, is_read=False).count()

    return render_template('dashboard/maintenance.html', reports=reports, unread_messages_count=unread_messages_count)

@main.route('/properties')
@login_required
def properties():
    if property.owner_id != current_user.owner_id and current_user.manager_id is None:
        abort(403)         
        flash('You do not have any properties associated with your account.', 'danger')
        return redirect(url_for('route.dashboard'))  

    properties = Property.query.filter_by(owner_id=current_user.owner_id).all()
    return render_template('dashboard/properties.html', properties=properties)

@main.route('/tenants')
def tenants():
    page = request.args.get('page', 1, type=int)
    per_page = 20

    # Eagerly load the 'currency' relationship
    owner = Owner.query.options(joinedload(Owner.user).joinedload(User.currency)).filter_by(user_id=current_user.id).first()

    active_tenants = RentalAgreement.query \
        .filter_by(owner=owner, status='active') \
        .order_by(RentalAgreement.id) \
        .paginate(page=page, per_page=per_page, error_out=False)

    # Calculate lease life percentage for each tenant
    for tenant in active_tenants.items:
        time_diff = tenant.date_end - tenant.date_start
        time_passed = datetime.utcnow() - datetime.combine(tenant.date_start, datetime.min.time())
        tenant.lease_life_percent = 100 - round((time_passed / time_diff * 100), 1)

    return render_template('dashboard/tenants.html', active_tenants=active_tenants)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in {'png', 'jpg', 'jpeg'}

# Ensure the directory exists using current_app
def ensure_upload_folder_exists():
    if not os.path.exists(current_app.config['UPLOAD_FOLDER_PROFILE']):
        os.makedirs(current_app.config['UPLOAD_FOLDER_PROFILE'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ['png', 'jpg', 'jpeg']


def active_rental_agreements():
    return RentalAgreement.query.filter(
        RentalAgreement.status == 'active',
        RentalAgreement.owner.has(user_id=current_user.id)
    ).count()

def pending_rental_agreements():
    return RentalAgreement.query.filter(
        RentalAgreement.status == 'pending',
        RentalAgreement.owner.has(user_id=current_user.id)
    ).count()

def expired_rental_agreements():
    return RentalAgreement.query.filter(
        RentalAgreement.status == 'expired',
        RentalAgreement.owner.has(user_id=current_user.id)
    ).count()

def count_active_maintainance_reports():
    count = db.session.query(MaintainanceReport).filter(
        MaintainanceReport.status == 'reported',
        MaintainanceReport.property_id.in_(
            db.session.query(Property.id).filter(Property.owner.has(user_id=current_user.id))
        )  
    ).count()
    return count

def count_resolved_maintainance_reports():
    count = db.session.query(MaintainanceReport).filter(
        MaintainanceReport.status == 'resolved',
        MaintainanceReport.property_id.in_(
            db.session.query(Property.id).filter(Property.owner.has(user_id=current_user.id))
        )
    ).count()
    return count

def get_expenses_summary():
    # Query to sum amounts grouped by sub_category where main_category is 'Expenses'
    expenses_summary = db.session.query(
        Transaction.sub_category,
        func.sum(Transaction.amount).label('total_amount')
    ).filter(
        Transaction.main_category == 'Expenses',
        Transaction.is_reconciled == True,

templates/dashboard/change_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}

{% block content %}
<main id="main" class="main">
    <div class="pagetitle"></div>
      <h1>Change Password</h1>
    <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('main.index')}}">Dashboard</a></li>
          <li class="breadcrumb-item"><a href="{{ url_for('profile_routes.profile_settings')}}">Profile Settings</a></li>
          <li class="breadcrumb-item active">Change Password</li>

        </ol>
    </nav>

    <section class="section dashboard">
        <div class="container">
            <form method="POST" action="{{ url_for('auth_routes.change_password') }}">
                {{ form.hidden_tag() }}
        
                <!-- Old Password -->
                <div class="form-group">
                    {{ form.old_password.label }}
                    {{ form.old_password(class="form-control") }}
                </div>
        
                <!-- New Password -->
                <div class="form-group">
                    {{ form.new_password.label }}
                    {{ form.new_password(class="form-control") }}
                </div>
        
                <!-- Confirm Password -->
                <div class="form-group">
                    {{ form.confirm_password.label }}
                    {{ form.confirm_password(class="form-control") }}
                </div>
        
                <!-- Submit Button -->
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        
            <a href="{{ url_for('profile_routes.profile_settings') }}">Back to Profile Settings</a>
        </div>
    </section>

  </main><!-- End #main -->
  {% endblock %}

templates/dashboard/maintenance.html
{% extends "base.html" %}
{% block title %}Manage Maintenance{% endblock %}

{% block content %}
  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Manage Maintenance</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('main.index')}}">Dashboard</a></li>
          <li class="breadcrumb-item active">Manage Maintenance</li>
        </ol>
      </nav>

    <section class="section dashboard">
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Manage Maintenance</h5>
              <table class="table">
                <thead>
                  <tr>
                    <th>Thumbnail</th>
                    <th>Date</th>
                    <th>Property</th>
                    <th>Maintenance Type</th>
                    <th>Description</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {% for report in reports %}
                  <tr>
                    <td>
                      {% if report.photo %}
                        <img src="{{ report.photo.url }}" alt="Thumbnail" style="width: 50px; height: auto;">
                      {% else %}
                        <img src="path/to/default-thumbnail.jpg" alt="No Image" style="width: 50px; height: auto;">
                      {% endif %}
                    </td>
                    <td>{{ report.reported_date.strftime('%Y-%m-%d') }}</td>
                    <td>{{ report.property.title }}</td>
                    <td>{{ report.maintainance_type }}</td>
                    <td>{{ report.description[:50] }}{% if report.description|length > 50 %}...{% endif %}</td>
                    <td>{{ 'Resolved' if report.status else 'Reported' }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/dashboard/properties.html
{% extends "base.html" %}
{% block title %}My Properties{% endblock %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"> 

<main id="main" class="main">

    <div class="pagetitle">
        <h1>My Properies</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">My Properties</li>
          </ol>
        </nav>
        <a href="{{ url_for('property_routes.manage_property') }}" class="btn btn-primary add-property-btn">Add Property</a>
      </div>
      
      <style>
        .add-property-btn {
          position: absolute;
          top: 90px; 
          right: 30px; 
        }
      </style>

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">

              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th>Photo</th>
                    <th>Title</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for property_data in properties %}
                        <tr>
                            <td>
                                {% if property_data.thumbnail %}
                                    <img src="{{ url_for('static', filename='uploads/listings/' ~ property_data.thumbnail.file_path) }}" alt="Thumbnail">
                                {% else %}
                                    No Photo
                                {% endif %}
                            </td>
                            <td>{{ property_data.property.title }}</td>
                            <td>{{ property_data.property.type }}</td>
                            <td>{{ property_data.listing_status }}</td>
                            <td><a href="{{ url_for('property_routes.edit_property', property_id=property_data.property.id) }}" class="btn btn-primary">Edit</a></td>

                            <td>
                                <a href="{{ url_for('property_routes.edit_property', property_id=property_data.property.id) }}">Edit</a>
                                <a href="{{ url_for('property_routes.property_details', property_id=property_data.property.id) }}">View</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->
{% endblock %}

templates/dashboard/tenants.html
{% extends "base.html" %}
{% block title %}Tenants{% endblock %}

{% block content %}
<main id="main" class="main">

  <div class="pagetitle">
    <h1>Tenants</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main.index')}}">Dashboard</a></li>
        <li class="breadcrumb-item active">Tenants</li>
      </ol>
    </nav>
  </div>

  <section class="section dashboard">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Active Tenants</h5>
            <table class="table">
              <thead>
                <tr>
                  <th>Tenant Name</th>
                  <th>Agreement</th>
                  <th>Lease Life</th>
                </tr>
              </thead>
              <tbody>
                {% for tenant in active_tenants.items %}
                <tr>
                  <td>
                    <img src="{{ url_for('static', filename='uploads/profile/' + (tenant.tenant.user.profile_picture or 'default.png')) }}" 
                         alt="{{ tenant.tenant.user.firstname }} {{ tenant.tenant.user.lastname }}" 
                         class="rounded-circle"> 
                    {{ tenant.tenant.user.name }} {{ tenant.tenant.user.lastname }}
                  </td>
                  <td>
                    <a href="{{ url_for('rental_routes.view_rental_agreement_pdf', agreement_id=tenant.id) }}"> 
                      View Agreement
                    </a>
                  </td>
                  <td>
                    <span>{{ tenant.lease_life_percent }}%</span> 
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% if active_tenants.has_prev %}
            <a href="{{ url_for('main.tenants', page=active_tenants.prev_num) }}">Previous</a>
            {% endif %}
            {% if active_tenants.has_next %}
            <a href="{{ url_for('main.tenants', page=active_tenants.next_num) }}">Next</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>

</main>
{% endblock %}